services:
  web:
    container_name: hello-django-web-dev
    hostname: hello-django-web
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    user: "${UID}:${GID}"
    volumes:
      - ./app/:/app/
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    command: python3 manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:16.3-alpine3.19
    container_name: hello-django-db-dev
    hostname: hello-django-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${SQL_DATABASE?Variable not set}
      - POSTGRES_USER=${SQL_USER?Variable not set}
      - POSTGRES_PASSWORD=${SQL_PASSWORD?Variable not set}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hello_django"]
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
